---
- hosts: 172.31.14.161
  become: yes
  tasks:
  - name: excute linux directly
    command:  hostname -f
    register: myresult

  - name: i want to display first task result
    debug:
      msg: "{{myresult}}"