---
- hosts: 172.31.14.161
  become: yes
  tasks:
  - include_tasks: myfiles.yml

  - name: create a folder
    file:
      path: /home/ubuntu/myfolder
      state: directory
  - name: i want to copy file
    copy:
      src: mystaticfile
      dest: /home/ubuntu.mystaticfile.txt


  - name: install apache2
    apt:
     name: apache2
     state: present
     