---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install web server on ubuntu16 nodes
    apt: 
      name: "{{mywebpackonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to start webserver on ubuntu16 nodes
    service: 
       name: "{{mywebpackonubutu}}"
       state: started
    when: ansible_os_family =="Debian"

  - name:  install web server on RedHat node
    yum:
      name: "{{mywebpackonReaHot}}"
      state: present
    when: ansible_os_family =="RedHat"
  - name: i want to start web servers on RedHat node
    service:
      name: "{{mywebpackonReaHot}}"
      state: started
    when: ansible_os_family =="RedHat"