---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install webserver on ubuntu16 nodes
    apt: 
      name: appache2
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to start webserver on ubuntu16 nodes
    service: 
       name: appache2
       state: started
    when: ansible_os_family =="Debian"

  - name: i want to install webserver on RedHat node
    yum:
      name: RedHat
      state: present
    when: ansible_os_family =="RedHat"


  - name: i want to start webservers on RedHat node
    service:
      name: RedHat
      state: started
    when: ansible_os_family =="RedHat"