---
# tasks file for mytom2role
- include_tasks: installjava.yml
- include_tasks: createusergroup.yml
- include_tasks: installtomcat.yml
- include_tasks: updatepermissions.yml
- include_tasks: tomcatservicefile.yml
- include_tasks: tomcatstart.yml
- include_tasks: tomuserconf.yml
- include_tasks: tomuserconf.yml
- include_tasks: tomcatrestart.yml
- include_tasks: deployjavaapplication.yml
- include_tasks: tomcatrestart.yml



